# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fgag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fgag
  pod 'React', :path => '../node_modules/react-native/'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'fgagTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
